"""initial schema

Revision ID: 490f719d4d16
Revises: 
Create Date: 2026-09-05 12:55:36.062661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '490f719d4d16'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytic_account',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('analytic_type', sa.Enum('INCOME', 'EXPENSE', name='analytic_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytic_account')),
    sa.UniqueConstraint('name', name=op.f('uq_analytic_account_name'))
    )
    op.create_table('chart_of_account',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('account_type', sa.Enum('ASSET', 'BANK', 'CASH', 'LIABILITY', 'CAPITAL', 'INCOME', 'EXPENSE', 'OTHER_EXPENSE', name='account_type'), nullable=False),
    sa.Column('is_receivable', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_payable', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chart_of_account')),
    sa.UniqueConstraint('code', name=op.f('uq_chart_of_account_code'))
    )
    op.create_index('ix_coa_active_name', 'chart_of_account', ['is_active', 'name'], unique=False)
    op.create_index('ix_coa_type_active', 'chart_of_account', ['account_type', 'is_active'], unique=False)
    op.create_table('contact',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('contact_type', sa.Enum('CUSTOMER', 'VENDOR', 'BOTH', name='contact_type'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact')),
    sa.UniqueConstraint('email', name=op.f('uq_contact_email'))
    )
    op.create_index('ix_contact_active_name', 'contact', ['is_active', 'name'], unique=False)
    op.create_table('doc_sequence',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('fiscal_year', sa.SmallInteger(), nullable=False),
    sa.Column('padding', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('next_number', mysql.BIGINT(unsigned=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_doc_sequence')),
    sa.UniqueConstraint('code', 'fiscal_year', name='uq_seq_code_year')
    )
    op.create_table('product_category',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_category')),
    sa.UniqueConstraint('name', name=op.f('uq_product_category_name'))
    )
    op.create_table('budget',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('responsible_contact_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'REVISED', 'CANCELLED', name='budget_status'), nullable=False),
    sa.Column('revises_budget_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('end_date >= start_date', name=op.f('ck_budget_dates')),
    sa.ForeignKeyConstraint(['responsible_contact_id'], ['contact.id'], name=op.f('fk_budget_responsible_contact_id_contact')),
    sa.ForeignKeyConstraint(['revises_budget_id'], ['budget.id'], name=op.f('fk_budget_revises_budget_id_budget')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budget'))
    )
    op.create_index('ix_budget_period', 'budget', ['start_date', 'end_date'], unique=False)
    op.create_index('ix_budget_status', 'budget', ['status', 'is_active'], unique=False)
    op.create_table('journal',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('journal_type', sa.Enum('SALES', 'PURCHASE', 'BANK', 'CASH', 'MISC', name='journal_type'), nullable=False),
    sa.Column('default_account_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['default_account_id'], ['chart_of_account.id'], name=op.f('fk_journal_default_account_id_chart_of_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal')),
    sa.UniqueConstraint('code', name=op.f('uq_journal_code'))
    )
    op.create_table('product',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('product_type', sa.Enum('GOODS', 'SERVICE', 'COMBO', name='product_type'), nullable=False),
    sa.Column('category_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('sales_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('purchase_cost', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('default_tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('income_account_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('expense_account_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['product_category.id'], name=op.f('fk_product_category_id_product_category')),
    sa.ForeignKeyConstraint(['expense_account_id'], ['chart_of_account.id'], name=op.f('fk_product_expense_account_id_chart_of_account')),
    sa.ForeignKeyConstraint(['income_account_id'], ['chart_of_account.id'], name=op.f('fk_product_income_account_id_chart_of_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product'))
    )
    op.create_index('ix_product_active_name', 'product', ['is_active', 'name'], unique=False)
    op.create_table('user',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('login_id', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ACCOUNTANT', 'PORTAL', name='user_role'), nullable=False),
    sa.Column('contact_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], name=op.f('fk_user_contact_id_contact')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email')),
    sa.UniqueConstraint('login_id', name=op.f('uq_user_login_id'))
    )
    op.create_table('budget_line',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('budget_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('analytic_account_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('analytic_type', sa.Enum('INCOME', 'EXPENSE', name='budget_line_analytic_type'), nullable=False),
    sa.Column('planned_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.CheckConstraint('planned_amount >= 0', name=op.f('ck_bl_planned')),
    sa.ForeignKeyConstraint(['analytic_account_id'], ['analytic_account.id'], name=op.f('fk_budget_line_analytic_account_id_analytic_account')),
    sa.ForeignKeyConstraint(['budget_id'], ['budget.id'], name=op.f('fk_budget_line_budget_id_budget')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budget_line')),
    sa.UniqueConstraint('budget_id', 'analytic_account_id', name='uq_bl')
    )
    op.create_table('company_setting',
    sa.Column('id', mysql.TINYINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('company_name', sa.String(length=128), nullable=False),
    sa.Column('books_lock_date', sa.Date(), nullable=True),
    sa.Column('receivable_account_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('payable_account_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('output_tax_account_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('input_tax_account_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('sales_journal_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('purchase_journal_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('bank_journal_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('cash_journal_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.CheckConstraint('id = 1', name=op.f('ck_company_singleton')),
    sa.ForeignKeyConstraint(['bank_journal_id'], ['journal.id'], name=op.f('fk_company_setting_bank_journal_id_journal')),
    sa.ForeignKeyConstraint(['cash_journal_id'], ['journal.id'], name=op.f('fk_company_setting_cash_journal_id_journal')),
    sa.ForeignKeyConstraint(['input_tax_account_id'], ['chart_of_account.id'], name=op.f('fk_company_setting_input_tax_account_id_chart_of_account')),
    sa.ForeignKeyConstraint(['output_tax_account_id'], ['chart_of_account.id'], name=op.f('fk_company_setting_output_tax_account_id_chart_of_account')),
    sa.ForeignKeyConstraint(['payable_account_id'], ['chart_of_account.id'], name=op.f('fk_company_setting_payable_account_id_chart_of_account')),
    sa.ForeignKeyConstraint(['purchase_journal_id'], ['journal.id'], name=op.f('fk_company_setting_purchase_journal_id_journal')),
    sa.ForeignKeyConstraint(['receivable_account_id'], ['chart_of_account.id'], name=op.f('fk_company_setting_receivable_account_id_chart_of_account')),
    sa.ForeignKeyConstraint(['sales_journal_id'], ['journal.id'], name=op.f('fk_company_setting_sales_journal_id_journal')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_setting'))
    )
    op.create_table('document',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('doc_type', sa.Enum('PURCHASE_ORDER', 'VENDOR_BILL', 'SALES_ORDER', 'CUSTOMER_INVOICE', name='document_doc_type'), nullable=False),
    sa.Column('doc_number', sa.String(length=32), nullable=False),
    sa.Column('partner_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('journal_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('source_document_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('doc_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('reference', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'POSTED', 'CANCELLED', name='document_status'), nullable=False),
    sa.Column('untaxed_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("due_date IS NULL OR doc_type IN ('VENDOR_BILL','CUSTOMER_INVOICE')", name=op.f('ck_doc_duedate')),
    sa.CheckConstraint('total_amount >= 0 AND untaxed_amount >= 0', name=op.f('ck_doc_totals')),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_document_created_by_user')),
    sa.ForeignKeyConstraint(['journal_id'], ['journal.id'], name=op.f('fk_document_journal_id_journal')),
    sa.ForeignKeyConstraint(['partner_id'], ['contact.id'], name=op.f('fk_document_partner_id_contact')),
    sa.ForeignKeyConstraint(['source_document_id'], ['document.id'], name=op.f('fk_document_source_document_id_document')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document')),
    sa.UniqueConstraint('doc_type', 'doc_number', name='uq_doc_number')
    )
    op.create_index('ix_doc_partner', 'document', ['partner_id', 'doc_type', 'status'], unique=False)
    op.create_index('ix_doc_source', 'document', ['source_document_id'], unique=False)
    op.create_index('ix_doc_type_status_date', 'document', ['doc_type', 'status', 'doc_date'], unique=False)
    op.create_table('payment',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('payment_number', sa.String(length=32), nullable=False),
    sa.Column('payment_type', sa.Enum('RECEIVE', 'SEND', name='payment_type'), nullable=False),
    sa.Column('method', sa.Enum('BANK', 'CASH', name='payment_method'), nullable=False),
    sa.Column('partner_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('journal_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', 'CANCELLED', name='payment_header_status'), nullable=False),
    sa.Column('created_by', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_pay_amount')),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_payment_created_by_user')),
    sa.ForeignKeyConstraint(['journal_id'], ['journal.id'], name=op.f('fk_payment_journal_id_journal')),
    sa.ForeignKeyConstraint(['partner_id'], ['contact.id'], name=op.f('fk_payment_partner_id_contact')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment')),
    sa.UniqueConstraint('payment_number', name='uq_pay_number')
    )
    op.create_index('ix_pay_partner', 'payment', ['partner_id', 'status'], unique=False)
    op.create_table('refresh_token',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('is_used', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_revoked', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_refresh_token_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_token')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_token_token_hash'))
    )
    op.create_index(op.f('ix_refresh_token_family_id'), 'refresh_token', ['family_id'], unique=False)
    op.create_table('document_line',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('document_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('line_no', sa.SmallInteger(), nullable=False),
    sa.Column('product_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('account_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('analytic_account_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.CheckConstraint('quantity > 0 AND unit_price >= 0 AND tax_rate >= 0', name=op.f('ck_dl_qty')),
    sa.ForeignKeyConstraint(['account_id'], ['chart_of_account.id'], name=op.f('fk_document_line_account_id_chart_of_account')),
    sa.ForeignKeyConstraint(['analytic_account_id'], ['analytic_account.id'], name=op.f('fk_document_line_analytic_account_id_analytic_account')),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('fk_document_line_document_id_document'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_document_line_product_id_product')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_line')),
    sa.UniqueConstraint('document_id', 'line_no', name='uq_docline_no')
    )
    op.create_index('ix_docline_analytic', 'document_line', ['analytic_account_id'], unique=False)
    op.create_table('journal_entry',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('entry_number', sa.String(length=32), nullable=False),
    sa.Column('journal_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('reference', sa.String(length=128), nullable=True),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', 'CANCELLED', name='journal_entry_status'), nullable=False),
    sa.Column('source_type', sa.Enum('MANUAL', 'VENDOR_BILL', 'CUSTOMER_INVOICE', 'PAYMENT', name='journal_entry_source_type'), nullable=False),
    sa.Column('source_document_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('source_payment_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('total_debit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_credit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('posted_by', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total_debit = total_credit', name=op.f('ck_je_balanced')),
    sa.ForeignKeyConstraint(['journal_id'], ['journal.id'], name=op.f('fk_journal_entry_journal_id_journal')),
    sa.ForeignKeyConstraint(['posted_by'], ['user.id'], name=op.f('fk_journal_entry_posted_by_user')),
    sa.ForeignKeyConstraint(['source_document_id'], ['document.id'], name=op.f('fk_journal_entry_source_document_id_document')),
    sa.ForeignKeyConstraint(['source_payment_id'], ['payment.id'], name=op.f('fk_journal_entry_source_payment_id_payment')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal_entry')),
    sa.UniqueConstraint('entry_number', name='uq_je_number'),
    sa.UniqueConstraint('source_document_id', name='uq_je_src_doc'),
    sa.UniqueConstraint('source_payment_id', name='uq_je_src_pay')
    )
    op.create_index('ix_je_status_date', 'journal_entry', ['status', 'entry_date'], unique=False)
    op.create_table('payment_allocation',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('payment_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('document_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('amount_allocated', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.CheckConstraint('amount_allocated > 0', name=op.f('ck_alloc_amt')),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('fk_payment_allocation_document_id_document')),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], name=op.f('fk_payment_allocation_payment_id_payment'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_allocation')),
    sa.UniqueConstraint('payment_id', 'document_id', name='uq_alloc')
    )
    op.create_index('ix_alloc_doc', 'payment_allocation', ['document_id'], unique=False)
    op.create_table('journal_entry_line',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('journal_entry_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('line_no', sa.SmallInteger(), nullable=False),
    sa.Column('account_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('partner_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('analytic_account_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('debit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.CheckConstraint('NOT (debit > 0 AND credit > 0)', name=op.f('ck_jel_oneside')),
    sa.CheckConstraint('debit >= 0 AND credit >= 0', name=op.f('ck_jel_nonneg')),
    sa.ForeignKeyConstraint(['account_id'], ['chart_of_account.id'], name=op.f('fk_journal_entry_line_account_id_chart_of_account')),
    sa.ForeignKeyConstraint(['analytic_account_id'], ['analytic_account.id'], name=op.f('fk_journal_entry_line_analytic_account_id_analytic_account')),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entry.id'], name=op.f('fk_journal_entry_line_journal_entry_id_journal_entry'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partner_id'], ['contact.id'], name=op.f('fk_journal_entry_line_partner_id_contact')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal_entry_line'))
    )
    op.create_index('ix_jel_account', 'journal_entry_line', ['account_id'], unique=False)
    op.create_index('ix_jel_analytic', 'journal_entry_line', ['analytic_account_id'], unique=False)
    op.create_index('ix_jel_entry', 'journal_entry_line', ['journal_entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_jel_entry', table_name='journal_entry_line')
    op.drop_index('ix_jel_analytic', table_name='journal_entry_line')
    op.drop_index('ix_jel_account', table_name='journal_entry_line')
    op.drop_table('journal_entry_line')
    op.drop_index('ix_alloc_doc', table_name='payment_allocation')
    op.drop_table('payment_allocation')
    op.drop_index('ix_je_status_date', table_name='journal_entry')
    op.drop_table('journal_entry')
    op.drop_index('ix_docline_analytic', table_name='document_line')
    op.drop_table('document_line')
    op.drop_index(op.f('ix_refresh_token_family_id'), table_name='refresh_token')
    op.drop_table('refresh_token')
    op.drop_index('ix_pay_partner', table_name='payment')
    op.drop_table('payment')
    op.drop_index('ix_doc_type_status_date', table_name='document')
    op.drop_index('ix_doc_source', table_name='document')
    op.drop_index('ix_doc_partner', table_name='document')
    op.drop_table('document')
    op.drop_table('company_setting')
    op.drop_table('budget_line')
    op.drop_table('user')
    op.drop_index('ix_product_active_name', table_name='product')
    op.drop_table('product')
    op.drop_table('journal')
    op.drop_index('ix_budget_status', table_name='budget')
    op.drop_index('ix_budget_period', table_name='budget')
    op.drop_table('budget')
    op.drop_table('product_category')
    op.drop_table('doc_sequence')
    op.drop_index('ix_contact_active_name', table_name='contact')
    op.drop_table('contact')
    op.drop_index('ix_coa_type_active', table_name='chart_of_account')
    op.drop_index('ix_coa_active_name', table_name='chart_of_account')
    op.drop_table('chart_of_account')
    op.drop_table('analytic_account')
    # ### end Alembic commands ###
